Update NetworkInterface.c
FreeRTOS/FreeRTOS-Plus-TCP pull request #1002
Opened 2023-08-10 10:05 UTC by microcris

The changes that I'm proposing are to make the driver to work in case of cable disconnection. 

Fix assertion failure when disconnecting the Ethernet cable

Description
-----------
In prvEMACHandlerTask, when xSendEventStructToIPTask, we have to pass network interface or it will fail the assertion in xSendEventStructToIPTask "configASSERT( pxInterface != NULL )".

In pxNXP1064_NetworkInterfaceInitialise, if xWaitPHY fails (for instance, the cable is not connected), the switch case will break without doing nothing and the prvEMACHandlerTask will be blocked waiting for the notification. We have to unblock it to try again in case of failure in xEMAC_WaitPHY.

Test Steps
-----------
With the original code, connect the Ethernet  cable, let the DHCP make what it has to make, disconnect the cable and you will get the following message:
Link down!
ASSERT ERROR " pxInterface != ((void *)0) ": file "../FreeRTOS_TCP/Source/FreeRTOS_IP_Utils.c" Line "823" function name "prvProcessNetworkDownEvent" 

Apply the fix and you will get:
Link down!
Network Down
Configuration successful.
Waiting for link to go up and auto-negotiation to complete.
Failed to get the link up.
Link down!
Network Down
Configuration successful.
Waiting for link to go up and auto-negotiation to complete.
Link up.Waiting for auto-negotiation to complete.
Auto-negotiation complete.

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-08-11 12:02 UTC, microcris commented
> Hi @microcris, Thanks for sharing the fix. Can you also share how you validated the same fix and the various tests that you did validate the functionalities on NXP1060.

Hello!

I'm running FreeRTOS and FreeRTOS-PLUS-TCP on a custom board based on NXP RT1064.
In this I'm running a DHCP client and a TCP socket server.

The board is getting a correct IP from a DHCP server, I'm able to connect a socket client that is running on a computer and I'm able to correctly exchange data between the computer and the board.

Is this enough? 

In this particular case, I don't know if I have to run all the tests that are in the folder "test".

2023-08-16 03:28 UTC, ActoryOu requested changes
Hi @microcris,
Sorry for late response. And thanks for your contribution!

Overall, the change works perfectly. I can disconnect/re-connect network successfully by unplug/re-plug ethernet cable.

There are two minor changes required. The format of FreeRTOS_printf is different with your change and it causes compilation errors. Please help to take a look.

Thanks!

2023-08-16 03:28 UTC, ActoryOu commented on source/portable/NetworkInterface/NXP1060/NetworkInterface.c
> +                        FreeRTOS_printf( "RX Receive Error\n" );
```suggestion
                        FreeRTOS_printf( ( "RX Receive Error\n" ) );
```

2023-08-16 03:28 UTC, ActoryOu commented on source/portable/NetworkInterface/NXP1060/NetworkInterface.c
> +                        FreeRTOS_printf( "RX Receive default" );
```suggestion
                        FreeRTOS_printf( ( "RX Receive default" ) );
```

2023-08-22 04:23 UTC, ActoryOu approved these changes

2023-08-22 04:50 UTC, shubnil approved these changes

2023-08-22 09:54 UTC, merged