Bump CBMC version to 5.95.1
FreeRTOS/FreeRTOS-Plus-TCP pull request #1153
Opened 2024-06-06 10:41 UTC by tautschnig

Description
-----------
This will make proofs use the latest stable release of CBMC.

Test Steps
-----------
Tested in CI

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------
n/a

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-06-06 12:29 UTC, shubnil approved these changes

2024-06-06 12:39 UTC, shubnil requested changes
Please fix the failing CBMC check

2024-06-07 10:37 UTC, shubnil approved these changes

2024-06-07 13:43 UTC, tony-josi-aws approved these changes

2024-06-17 09:03 UTC, merged