TCP_WIN: fix compile warning on x86_64
FreeRTOS/FreeRTOS-Plus-TCP pull request #148
Opened 2021-01-08 17:16 UTC by twpedersen

Fix the following warning when building for 64 bit:

warning: conversion from ‘long unsigned int’ to ‘uint32_t’ {aka ‘unsigned int’} changes value from ‘18446744073709551615’ to ‘4294967295’ [-Woverflow]
             uint32_t ulReturn = ~0UL;
                                 ^

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-01-08 20:51 UTC, AniruddhaKanhere requested changes
Hello @twpedersen, thanks for taking the time to note this warning and creating a PR for this. 
Can you please have a look at the suggested change(s) to keep the code in line with the FreeRTOS code formatting standard? Thanks!

2021-01-08 20:51 UTC, AniruddhaKanhere commented on FreeRTOS_TCP_WIN.c
> +            uint32_t ulReturn = (uint32_t) ~0UL;
```suggestion
            uint32_t ulReturn = ( ( uint32_t ) ~0UL );
```

2021-01-11 19:40 UTC, AniruddhaKanhere approved these changes

2021-01-13 07:32 UTC, cobusve approved these changes

2021-01-14 02:29 UTC, merged