Fix CBMC proof of ProcessReceivedUDPPacket
FreeRTOS/FreeRTOS-Plus-TCP pull request #183
Opened 2021-01-28 06:39 UTC by AniruddhaKanhere

Description
-----------

This change was required since the functioning has changed as compared to the IPv4 code base. There is a new concept of Interfaces and Endpoints which needs to be addressed in the proofs dealing with them.
This should technically be considered as the proofs being added rather than the proofs being changed since this is a new library (although based on IPv4 code base).

Test Steps
-----------

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-01-28 21:39 UTC, markrtuttle requested changes
Same comment about nondet_bool followed by assume nonnull.

2021-01-29 02:09 UTC, AniruddhaKanhere commented
> Same comment about nondet_bool followed by assume nonnull.

I have added that in anticipation of using the --malloc-can-fail flag. But when I just use a malloc, the use of __CPROVER_assume seems weird.
I am thinking to add the flag and clean up all the proofs all at one with an additional PR - since there were 12 or so proofs which did not need modification.
One such simple PR doing just one thing will be extremely easy to review.
What do you think @markrtuttle?

2021-01-29 21:22 UTC, markrtuttle commented
> One such simple PR doing just one thing will be extremely easy to review.
> What do you think @markrtuttle?

Famous last words.  I've said the same thing once upon a time.  :-)

2021-01-29 21:24 UTC, markrtuttle approved these changes

2021-01-29 21:51 UTC, n9wxu approved these changes

2021-02-01 01:44 UTC, merged