Fix CBMC proof of prvProcessEthernetPacket
FreeRTOS/FreeRTOS-Plus-TCP pull request #184
Opened 2021-01-28 07:01 UTC by AniruddhaKanhere

Description
-----------

This change was required since the functioning has changed as compared to the IPv4 code base. There is a new concept of Interfaces and Endpoints which needs to be addressed in the proofs dealing with them.
This should technically be considered as the proofs being added rather than the proofs being changed since this is a new library (although based on IPv4 code base).

Test Steps
-----------

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-01-28 21:40 UTC, markrtuttle requested changes

2021-01-28 21:40 UTC, markrtuttle commented on test/cbmc/proofs/prvProcessEthernetPacket/prvProcessEthernetPacket_harness.c
> +    __CPROVER_assert( pxNetworkBuffer, "NetworkBuffer cannot be NULL" );
Compare with 0 or NULL

2021-01-29 02:12 UTC, AniruddhaKanhere commented on test/cbmc/proofs/prvProcessEthernetPacket/prvProcessEthernetPacket_harness.c
> +    __CPROVER_assert( pxNetworkBuffer, "NetworkBuffer cannot be NULL" );
Done

2021-01-29 21:24 UTC, markrtuttle approved these changes

2021-01-29 21:52 UTC, n9wxu approved these changes

2021-02-01 02:11 UTC, merged