Fix CBMC proof of ProcessIPPacket
FreeRTOS/FreeRTOS-Plus-TCP pull request #185
Opened 2021-01-28 07:20 UTC by AniruddhaKanhere

Description
-----------

This change was required since the functioning has changed as compared to the IPv4 code base. There is a new concept of Interfaces and Endpoints which needs to be addressed in the proofs dealing with them.
This should technically be considered as the proofs being added rather than the proofs being changed since this is a new library (although based on IPv4 code base).

Test Steps
-----------

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-01-28 21:43 UTC, markrtuttle requested changes

2021-01-28 21:43 UTC, markrtuttle commented on test/cbmc/proofs/parsing/ProcessIPPacket/ProcessIPPacket_harness.c
> +    pxNetworkBuffer->pucEthernetBuffer = nondet_bool() ? NULL : malloc( ipTOTAL_ETHERNET_FRAME_SIZE );
Surprised buffer length is not relates to pxNextorkBuffer->xDataLength.  Is this a mistake?

2021-02-12 00:25 UTC, markrtuttle approved these changes

2021-02-12 16:23 UTC, n9wxu approved these changes

2021-02-12 18:31 UTC, merged