Update files referencing aws_application_version.h to use iot_application_version.h
FreeRTOS/FreeRTOS-Plus-TCP pull request #188
Opened 2021-02-03 23:13 UTC by paulbartell

Update files referencing aws_application_version.h to use iot_application_version.h

Description
-----------
Update references to the aws_application_version.h file due to the configuration rename in the amazon-freertos repository.

Test Steps
-----------
Verify that builds for the pic32mzef platform are successful.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-02-06 01:11 UTC, AniruddhaKanhere requested changes

2021-02-08 18:00 UTC, paulbartell commented on portable/NetworkInterface/pic32mzef/NetworkInterface_eth.c
> +        #include "iot_application_version.h"
I'll update this PR to remove the the "_Command_Version" function and any references.

2021-02-08 20:54 UTC, aggarg approved these changes

2021-02-08 21:37 UTC, AniruddhaKanhere approved these changes
Some background: This is a command which can be called from terminal. But since the command pertains to aws and returns the version of freertos (and not of FreeRTOS+TCP), it is a good idea to remove the command and the respective header file used.
The command doesn't seem to be used in any demos etc.
Furthermore, the command being removed just prints stuff and will not cause any logical change.

Thanks @paulbartell for this PR.

2021-02-08 21:37 UTC, merged