IPv6/multi : lowered the complexity of FreeRTOS_ARP.c
FreeRTOS/FreeRTOS-Plus-TCP pull request #254
Opened 2021-05-18 16:57 UTC by htibosch

Description
-----------
In this PR I have split-up several functions in FreeRTOS_ARP.c
The complexity scores are now between 0 and 8, coming from :
~~~
Score | ln-ct | nc-lns| file-name(line): proc-name
   15     114      61   FreeRTOS_ARP.c(80): eARPProcessPacket
   37     155      94   FreeRTOS_ARP.c(239): vARPRefreshCacheEntry
total nc-lns      400
~~~
These are the new helper functions:
~~~
static eARPLookupResult_t prvCacheLookup( uint32_t ulAddressToLookup,
                                          MACAddress_t * const pxMACAddress,
                                          NetworkEndPoint_t ** ppxEndPoint );

static void vARPProcessPacketRequest( ARPPacket_t * pxARPFrame,
                                      NetworkEndPoint_t * pxTargetEndPoint,
                                      uint32_t ulSenderProtocolAddress );

static void vARPProcessPacketReply( ARPPacket_t * pxARPFrame,
                                    NetworkEndPoint_t * pxTargetEndPoint,
                                    uint32_t ulSenderProtocolAddress );

static eARPLookupResult_t eARPGetCacheEntryGateWay( uint32_t * pulIPAddress,
                                                    MACAddress_t * const pxMACAddress,
                                                    struct xNetworkEndPoint ** ppxEndPoint );

static void vARPSendRequestPacket( NetworkBufferDescriptor_t * pxNetworkBuffer );

static void prvFindCachEntry( const MACAddress_t * pxMACAddress,
                              const uint32_t ulIPAddress,
                              struct xNetworkEndPoint * pxEndPoint,
                              CacheLocation_t * pxLocation );
~~~

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-06-09 02:48 UTC, AniruddhaKanhere requested changes

2021-06-09 07:26 UTC, htibosch reviewed
Thanks for reviewing, you had some good points.

2021-06-09 07:26 UTC, htibosch commented on FreeRTOS_ARP.c
> +            if( pxSourceEndPoint != NULL )
Oops, I did not compile/test with `ipconfigARP_USE_CLASH_DETECTION` defined. Thanks for seeing this.

2021-06-09 07:26 UTC, htibosch commented on FreeRTOS_ARP.c
> +        prvFindCachEntry( pxMACAddress, ulIPAddress, pxEndPoint, &( xLocation ) );
`s/prvFindCachEntry/prvFindCacheEntry/g`

2021-06-09 07:26 UTC, htibosch commented on include/FreeRTOS_ARP.h
> + * It is used as a parameter for the function prvFindCachEntry().*/
Done

2021-06-10 21:08 UTC, AniruddhaKanhere commented
@htibosch, this comment needs to be addressed: "xAddressIsLocal is out of scope here. It was present in the vARPRefreshCacheEntry."

2021-06-16 01:08 UTC, AniruddhaKanhere approved these changes

2021-06-16 01:29 UTC, cobusve approved these changes

2021-06-16 03:35 UTC, merged