Reduced complexity FreeRTOS_TCP_WIN
FreeRTOS/FreeRTOS-Plus-TCP pull request #280
Opened 2021-07-27 14:45 UTC by htibosch

Description
-----------
The module FreeRTOS+TCP_WIN.c had 4 functions with a high score on complexity. I cut down their size by moving some code the helper functions:

lTCPWindowRxCheck()  score 66
	prvTCPWindowRx_ExpectedRX()
	prvTCPWindowRx_UnexpectedRX()

lTCPWindowTxAdd()  score 35
	prvTCPWindowTxAdd_FrontSegment()

ulTCPWindowTxGet()  score 43
	pxTCPWindowTx_GetWaitQueue()
	pxTCPWindowTx_GetTXQueue()

prvTCPWindowTxCheckAck()  score 25
	prvTCPWindowTxCheckAck_CalcSRTT()

Test Steps
-----------
I tested by transferring files in both directions while dropping random packets in both directions.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-08-03 19:36 UTC, AniruddhaKanhere requested changes

2021-08-04 06:37 UTC, htibosch commented on FreeRTOS_TCP_WIN.c
> +/*					} */
I disabled the comment with double slashes, uncrustify replaced them by proper C comments `/* */`.
This is a very old logging statement, which increases the complexity of the function from 6 to 14.
As I haven't enabled any TCP_WIN logging for many years, I will take it away.

2021-08-04 06:44 UTC, htibosch commented on FreeRTOS_TCP_WIN.c
> +                /* A negative value will be returned to indicate than error. */
Done so, thanks.

2021-08-05 20:12 UTC, AniruddhaKanhere approved these changes

2021-08-06 22:02 UTC, dan4thewin approved these changes

2021-08-07 20:04 UTC, merged