Fix various compiler warnings
FreeRTOS/FreeRTOS-Plus-TCP pull request #494
Opened 2022-06-23 16:32 UTC by holden-zenith

This fixes various compiler warnings found when testing with stm32f7

2022-06-23 22:38 UTC, AniruddhaKanhere requested changes
Thank you @holden-zenith for this PR.
I have one suggested change, can you please take a look?

2022-06-23 22:38 UTC, AniruddhaKanhere commented on source/include/FreeRTOSIPConfigDefaults.h
> +            #warning Do not define FreeRTOS_debug_print if ipconfigHAS_DEBUG_PRINTF is set to 0
The `#warning` option is not supported on windows simulator.

Since this file is not specific to STM, I think we should not make this change...

2022-06-23 22:38 UTC, AniruddhaKanhere commented on source/include/FreeRTOSIPConfigDefaults.h
> +            #warning Do not define FreeRTOS_print if ipconfigHAS_PRINTF is set to 0
Same here.

2022-06-24 13:43 UTC, htibosch approved these changes
Turn the warning into an error, I'm OK with that change.
Thank you

**EDIT**
Sorry I pressed on a link from my email client and I only saw part of your PR. I will read (and review) more.

2022-06-24 20:08 UTC, AniruddhaKanhere approved these changes
Thanks for this PR @holden-zenith. I am approving this.

We'll need one more review - I am asking for it. Once we have that, we can merge the PR!

2022-06-24 22:20 UTC, paulbartell approved these changes

2022-06-24 22:22 UTC, merged