Change in UDP process flow to drop packet for invalid IPv4 payload length
FreeRTOS/FreeRTOS-Plus-TCP pull request #716
Opened 2023-02-14 17:07 UTC by kar-rahul-aws

Change in UDP process flow to drop packet for invalid IPv4 payload length
Description
-----------
Change in prvProcessUDPPacket function, add condition for Release buffer
Checking the frame type only for IPv4, since the same check will give unwanted results for IPv6

Test Steps
-----------
Code is building with the changes

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-02-14 17:11 UTC, kar-rahul-aws commented
/bot run uncrustify

2023-02-14 17:20 UTC, shubnil requested changes
There are lot of unwanted changes which is probably because of wrong base branch. You will have to rebase the local branch and push the PR again. The issue is same as https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/715

2023-02-14 17:30 UTC, shubnil commented
My bad, uncrustify is adding the extra indentations

2023-02-14 17:30 UTC, shubnil approved these changes

2023-02-15 04:20 UTC, moninom1 approved these changes

2023-02-15 04:34 UTC, merged