Unit Test for DHCP
FreeRTOS/FreeRTOS-Plus-TCP pull request #902
Opened 2023-06-07 05:27 UTC by kar-rahul-aws

Description
-----------
This Pr adds 100% coverage for DHCP Unit Test

Test Steps
-----------
```
cmake -S test/unit-test -B test/unit-test/build/ -DCMAKE_BUILD_TYPE=Debug
make -C test/unit-test/build/ all
```

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [x] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-06-07 09:34 UTC, ActoryOu requested changes

2023-06-08 07:24 UTC, kar-rahul-aws commented
/bot run uncrustify

2023-06-09 01:31 UTC, ActoryOu requested changes

2023-06-09 01:31 UTC, ActoryOu commented on source/FreeRTOS_DHCP.c
>                  xDHCPSocketUserCount = 1;
Should we reset the socket to NULL if bind returns fail?

2023-06-09 03:48 UTC, ActoryOu approved these changes

2023-06-09 03:56 UTC, moninom1 approved these changes

2023-06-09 04:08 UTC, shubnil approved these changes

2023-06-09 04:13 UTC, merged