Add CBMC proof for IPv6 FreeRTOS_Routing functions
FreeRTOS/FreeRTOS-Plus-TCP pull request #912
Opened 2023-06-12 10:44 UTC by moninom1

Description
-----------
Add CBMC proof for following functions :
FreeRTOS_MatchingEndpoint
pxEasyFit

Also validates :
xIPv6_GetIPType
FreeRTOS_FirstEndPoint
FreeRTOS_NextEndPoint

Test Steps
-----------
```
python prepare.py
make
```

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [x] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-06-14 09:13 UTC, moninom1 commented
/bot run uncrustify

2023-06-15 04:27 UTC, moninom1 commented on test/cbmc/proofs/Routing/MatchingEndpoint/MatchingEndpoint_harness.c
> +    pxNetworkEndPoints = ( NetworkEndPoint_t * ) malloc( sizeof( NetworkEndPoint_t ) );
```suggestion
    pxNetworkEndPoints = ( NetworkEndPoint_t * ) safeMalloc( sizeof( NetworkEndPoint_t ) );
```

2023-06-16 07:25 UTC, ActoryOu requested changes

2023-06-16 07:25 UTC, ActoryOu commented on test/cbmc/proofs/Routing/MatchingEndpoint/Makefile.json
> +      "--unwindset pxEasyFit.0:5",
Can we set a macro to describe what 5 is?

2023-06-16 07:25 UTC, ActoryOu commented on test/cbmc/proofs/Routing/MatchingEndpoint/Makefile.json
> +      "--unwindset pxEasyFit.0:5",
Like [Aniruddha commented](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/896#discussion_r1230101287) in another PR.

2023-06-16 07:30 UTC, ActoryOu requested changes

2023-06-16 07:30 UTC, ActoryOu commented on test/cbmc/proofs/Routing/MatchingEndpoint/MatchingEndpoint_harness.c
> +    pxNetworkEndPoints->pxNext = NULL;
Should we use nondet_bool to append second endpoint to the list?

2023-06-16 15:36 UTC, ActoryOu approved these changes

2023-06-19 10:06 UTC, shubnil approved these changes

2023-06-19 15:38 UTC, merged