Add CBMC proof for ICMP functions
FreeRTOS/FreeRTOS-Plus-TCP pull request #914
Opened 2023-06-13 11:04 UTC by tony-josi-aws

Description
-----------
This PR adds CBMC proofs for the following ICMP functions:

- ProcessICMPPacket
- prvProcessICMPEchoReply
- prvProcessICMPEchoRequest

Test Steps
-----------
Ran CBMC on the proofs

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-06-16 08:59 UTC, ActoryOu requested changes

2023-06-16 08:59 UTC, ActoryOu commented on test/cbmc/proofs/ICMP/ProcessICMPEchoRequest/ProcessICMPEchoRequest_harness.c
> +    ICMPPacket_t * const pxICMPPacket = malloc( sizeof( ICMPPacket_t ) );
Please use safeMalloc instead.

2023-06-16 08:59 UTC, ActoryOu commented on test/cbmc/proofs/ICMP/ProcessICMPPacket/ProcessICMPPacket_harness.c
> +
```suggestion

/* CBMC includes. */
```

2023-06-16 08:59 UTC, ActoryOu commented on test/cbmc/proofs/ICMP/ProcessICMPPacket/ProcessICMPPacket_harness.c
> +    eFrameProcessingResult_t retVal;
Please FreeRTOS follow naming rule.

2023-06-16 08:59 UTC, ActoryOu commented on test/cbmc/proofs/ICMP/ProcessICMPPacket/ProcessICMPPacket_harness.c
> +    ICMPPacket_t * const pxICMPPacket = malloc( sizeof( ICMPPacket_t ) );
Please use safeMalloc instead.

2023-06-19 01:55 UTC, ActoryOu approved these changes

2023-06-19 10:09 UTC, shubnil approved these changes

2023-06-19 10:14 UTC, merged