Readme and History Changes for V4.0.0-rc3 Release
FreeRTOS/FreeRTOS-Plus-TCP pull request #944
Opened 2023-06-28 11:24 UTC by moninom1

Description
-----------

- Update README.md
- Update History.txt

Test Steps
-----------

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-06-29 08:48 UTC, moninom1 commented
/bot run uncrusitfy

2023-06-29 08:48 UTC, moninom1 commented
/bot run uncrustify

2023-06-29 10:15 UTC, shubnil commented on History.txt
> +		+ Added build separation in FreeRTOS+TCP stack to make the library more lightweight and optimized for users,
Can we add something like this "Added build separation in FreeRTOS+TCP stack to make the library more modular. This enables the users to compile and create a low footprint binary with only the required functionalities."

2023-06-29 11:05 UTC, amazonKamath requested changes

2023-06-30 08:07 UTC, shubnil approved these changes

2023-06-30 08:35 UTC, amazonKamath approved these changes

2023-06-30 09:39 UTC, merged